### PR TITLE
Add upstream Bison3 fixes

### LINKED ISSUE #3: ELIFECYCLE error while installing
I was trying to install using `npm i mathematical` but i'm getting the following error
```shell
$ npm install mathematical
npm WARN package.json instapush@0.0.7 No repository field.
npm http GET https://registry.npmjs.org/mathematical
npm http 304 https://registry.npmjs.org/mathematical

> mathematical@0.1.1 preinstall /var/www/learnise/app/node_modules/mathematical
> script/compile_mtex2MML && npm install --production --ignore-scripts && node-gyp rebuild

rm -f y.tab.* lex.yy.c mtex2MML *.o *.output *.so *.dll *.sl *.bundle mtex2MML_ruby.c
cc -fPIC -c -o string_extras.o string_extras.c
cc -fPIC -c -o parse_extras.o parse_extras.c
cc -fPIC -c -o color_definitions.o color_definitions.c
bison -y  -v -p mtex2MML_yy -d mtex2MML.y
mtex2MML.y: warning: 2017 shift/reduce conflicts [-Wconflicts-sr]
mtex2MML.y: warning: 166 reduce/reduce conflicts [-Wconflicts-rr]
flex -Pmtex2MML_yy -olex.yy.c mtex2MML.l
mtex2MML.l:1325: warning, rule cannot be matched
cc  -c -o lex.yy.o string_extras.o parse_extras.o color_definitions.o lex.yy.c
cc: warning: string_extras.o: linker input file unused because linking not done
cc: warning: parse_extras.o: linker input file unused because linking not done
cc: warning: color_definitions.o: linker input file unused because linking not done
cc  -c -o y.tab.o y.tab.c
mtex2MML.y: In function ‘mtex2MML_yyparse’:
mtex2MML.y:306:25: error: ‘ret_str’ undeclared (first use in this function)
   char ** r = (char **) ret_str;
                         ^
mtex2MML.y:306:25: note: each undeclared identifier is reported only once for each function it appears in
mtex2MML.y:1927:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:1936:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:1948:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:1957:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:1966:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:1975:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:1984:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:1993:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:2002:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:2011:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:2020:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:2032:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:2041:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:2052:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y:2067:24: warning: passing argument 1 of ‘mtex2MML_free_string’ discards ‘const’ qualifier from pointer target type
   mtex2MML_free_string(pipe_chars);
                        ^
mtex2MML.y:279:7: note: expected ‘char *’ but argument is of type ‘const char *’
  void mtex2MML_free_string (char * str)
       ^
mtex2MML.y:2068:24: warning: passing argument 1 of ‘mtex2MML_free_string’ discards ‘const’ qualifier from pointer target type
   mtex2MML_free_string(column_align);
                        ^
mtex2MML.y:279:7: note: expected ‘char *’ but argument is of type ‘const char *’
  void mtex2MML_free_string (char * str)
       ^
mtex2MML.y:2072:22: warning: initialization discards ‘const’ qualifier from pointer target type
   char *pipe_chars = vertical_pipe_extract($4);
                      ^
mtex2MML.y:2073:24: warning: initialization discards ‘const’ qualifier from pointer target type
   char *column_align = remove_excess_pipe_chars($4);
                        ^
mtex2MML.y:2074:20: warning: initialization discards ‘const’ qualifier from pointer target type
   char *row_data = combine_row_data(&environment_data_stack);
                    ^
mtex2MML.y: In function ‘mtex2MML_parse’:
mtex2MML.y:2375:12: error: too many arguments to function ‘mtex2MML_yyparse’
   result = mtex2MML_yyparse (&mathml);
            ^
y.tab.c:63:25: note: declared here
 #define yyparse         mtex2MML_yyparse
                         ^
y.tab.c:3634:1: note: in expansion of macro ‘yyparse’
 yyparse (void)
 ^
mtex2MML.y: In function ‘mtex2MML_filter’:
mtex2MML.y:2403:10: error: too many arguments to function ‘mtex2MML_yyparse’
   return mtex2MML_yyparse (0);
          ^
y.tab.c:63:25: note: declared here
 #define yyparse         mtex2MML_yyparse
                         ^
y.tab.c:3634:1: note: in expansion of macro ‘yyparse’
 yyparse (void)
 ^
Makefile:32: recipe for target 'y.tab.o' failed
make: *** [y.tab.o] Error 1
npm ERR! mathematical@0.1.1 preinstall: `script/compile_mtex2MML && npm install --production --ignore-scripts && node-gyp rebuild`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mathematical@0.1.1 preinstall script.
npm ERR! This is most likely a problem with the mathematical package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     script/compile_mtex2MML && npm install --production --ignore-scripts && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mathematical
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mathematical"
npm ERR! cwd /var/www/learnise/app
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/learnise/app/npm-debug.log
npm ERR! not ok code 0

```

### PR DESCRIPTION
**Pull request by gjtorikian**
Closes https://github.com/gjtorikian/mathematical-node/issues/3.

/cc @iyogeshjoshi Could you pull this repo down and switch to this branch? If it allows you to build and run the tests I'm going to publish a new version. Thanks for the report.

### CODE REVIEW

**Comment by iyogeshjoshi** [comment]
@gjtorikian I pulled this branch and yes this fixes the installation problem with ubuntu, though it needs `sudo` rights for it, I think you would like to specify this on README file :). Thanks!

**Comment by gjtorikian** [comment]
Cool. Real quick, could you also try `grunt test` in the branch? I was having some intermittent problems, but I'm also running a VM.

**Comment by iyogeshjoshi** [comment]
I think there is some problem with your pre installation script i think its `bootstrap`. I tried running grunt test it throws the following error
```shell
iyogeshjoshi@mathematical-node$ grunt test
Running "coffee:glob_to_multiple" (coffee) task

Running "coffeelint:gruntfile" (coffeelint) task
>> 1 file lint free.

Running "coffeelint:src" (coffeelint) task
>> 2 files lint free.

Running "coffeelint:test" (coffeelint) task
>> 9 files lint free.

Running "cpplint" task
 ✓ src/processor.cc
 ✓ src/processor.h

Running "shell:compile_mtex2MML" (shell) task
script/compile_mtex2MML: line 5: cd: deps/mtex2MML/src: No such file or directory
Warning: Command failed: script/compile_mtex2MML: line 5: cd: deps/mtex2MML/src: No such file or directory
 Use --force to continue.

Aborted due to warnings.
```
Although if go to your `scripts/` folder and executes `bootstrap` manually everything works properly.
While doing `npm install` it is not pulling the sub-modules. please check.

**Comment by gjtorikian** [comment]
All right--I made a slight change, if you'd like to try again.

**Comment by iyogeshjoshi** [comment]
@gjtorikian hey I don't know what you did, but now it is installing smoothly. Nice work! :+1:

**Pull request merged**
